logger:
  file: /open5gs/install/var/log/open5gs/amf.log

amf:
  sbi:
    server:
      - address: 10.1.1.18
        port: 7777
    client:
      scp:
        - uri: http://10.1.1.11:7777

  ngap:
    server:
      - address: 10.1.1.18

  metrics:
    server:
      - address: 10.1.1.18
        port: 9090

  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 2
        set: 1

  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 7

  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1

  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]

  network_name:
    full: Open5GS
    short: Open5GS

  network_feature_support_5gc:
    enable: true
    emf: 2
    imsVoPS: 0
    emc: 0
    mcsi: 0
    atsss: 0
    5g_lcs: 0
    n3_data: 0
    sorAMF: 0

  amf_name: open5gs-amf0

scp:
  sbi:
    client:
      nrf:
        - uri: http://10.1.1.10:7777