# srsRAN Project gNB configuration for ZMQ with srsUE - localhost version
# Based on gnb_rf_b210_fdd_srsUE.yml adapted for ZMQ

cu_cp:
  amf:
    addr: 127.0.0.1                 # AMF address on localhost
    port: 38412                     # AMF NGAP port  
    bind_addr: 127.0.0.1            # gNB bind address on localhost
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001,base_srate=23.04e6
  srate: 23.04
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 368500                  # DL ARFCN for band 3
  band: 3                           # Band 3 (1800 MHz FDD)
  channel_bandwidth_MHz: 10         # 10 MHz bandwidth (52 PRBs)
  common_scs: 15                    # 15 kHz subcarrier spacing
  plmn: "00101"                     # PLMN matching AMF
  tac: 7                            # TAC matching AMF
  pci: 1                            # Physical Cell ID
  
  # PDCCH configuration for srsUE compatibility
  pdcch:
    dedicated:
      ss2_type: common
      dci_format_0_1_and_1_1: false
    common:
      ss0_index: 0
      coreset0_index: 6            # CORESET#0 index for 10 MHz bandwidth
  
  # PRACH configuration
  prach:
    prach_config_index: 1           # FDD PRACH configuration
    
  # MCS tables for srsUE
  pdsch:
    mcs_table: qam64
  pusch:
    mcs_table: qam64

log:
  all_level: info
  phy_level: info
  mac_level: info
  rlc_level: info
  pdcp_level: info
  rrc_level: info
  ngap_level: info
  hex_max_size: 32