# srsRAN gNodeB configuration with loopback interfaces

cu_cp:
  amf:
    addr: 127.0.0.4                 # AMF on lo4
    port: 38412
    bind_addr: 127.0.0.11           # gNodeB on lo11 (for N2 and GTP-U)
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001,base_srate=23.04e6
  srate: 23.04
  tx_gain: 75
  rx_gain: 75

cell_cfg:
  dl_arfcn: 368500
  band: 3
  channel_bandwidth_MHz: 10       # 10 MHz for testing
  common_scs: 15
  plmn: "00101"
  tac: 7
  pci: 1
  
  pdcch:
    dedicated:
      ss2_type: common
      dci_format_0_1_and_1_1: false
    common:
      ss0_index: 0
      coreset0_index: 6           # Correct for band 3, 10 MHz
  
  prach:
    prach_config_index: 1
    
  pdsch:
    mcs_table: qam64
  pusch:
    mcs_table: qam64

log:
  # Log will be redirected to stdout and captured by script
  all_level: info