# srsRAN Project gNB configuration for ZMQ with srsUE
# Matches official srsRAN ZMQ tutorial configuration
# Adapted for Albor multi-loopback Open5GS deployment

cu_cp:
  amf:
    addr: 127.0.0.4                 # AMF address (multi-loopback setup)
    port: 38412                     # AMF NGAP port  
    bind_addr: 127.0.0.11           # gNB bind address (multi-loopback setup)
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001,base_srate=23.04e6
  srate: 23.04
  tx_gain: 75                       # Match srsRAN tutorial
  rx_gain: 75                       # Match srsRAN tutorial

cell_cfg:
  dl_arfcn: 368500                  # DL ARFCN for band 3
  band: 3                           # Band 3 (1800 MHz FDD)
  channel_bandwidth_MHz: 20         # 20 MHz bandwidth 
  common_scs: 15                    # 15 kHz subcarrier spacing
  plmn: "00101"                     # PLMN matching AMF
  tac: 7                            # TAC matching AMF
  pci: 1                            # Physical Cell ID
  
  # PDCCH configuration per srsRAN tutorial
  pdcch:
    common:
      ss0_index: 0
      coreset0_index: 13            # CORESET#0 index for band 3, 20 MHz
    dedicated:
      ss2_type: common
      dci_format_0_1_and_1_1: false
  
  # PRACH configuration per srsRAN tutorial
  prach:
    prach_config_index: 1           # FDD PRACH configuration
    total_nof_ra_preambles: 64      # From srsRAN tutorial
    nof_ssb_per_ro: 1               # From srsRAN tutorial
    nof_cb_preambles_per_ssb: 64    # From srsRAN tutorial
    
  # MCS tables for srsUE
  pdsch:
    mcs_table: qam64
  pusch:
    mcs_table: qam64

log:
  filename: /tmp/gnb.log
  all_level: info

pcap:
  mac_enable: enable
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: enable
  ngap_filename: /tmp/gnb_ngap.pcap