logger:
  file: /open5gs/install/var/log/open5gs/amf.log
  level: info

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.

amf:
  sbi:
    server:
      - address: 10.53.1.2
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.200:7777
  ngap:
    server:
      - address: 10.53.1.2
        port: 38412
  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 7
  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1
          sd: 1
  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: Open5GS
  amf_name: open5gs-amf0
  time:
    t3502:
      value: 720   # 12 minutes
    t3512:
      value: 3240  # 54 minutes
    t3522:
      value: 6     # 6 seconds
    t3550:
      value: 6     # 6 seconds
    t3560:
      value: 6     # 6 seconds
    t3570:
      value: 6     # 6 seconds
    t3588:
      value: 6     # 6 seconds