db_uri: mongodb://127.0.0.2/open5gs

logger:
  level: info

pcf:
  sbi:
    server:
      - address: 127.0.0.8
        port: 7777
    client:
      nrf:
        - uri: http://127.0.0.3:7777
  metrics:
    server:
      - address: 127.0.0.8
        port: 9090