logger:
  level: info

upf:
  pfcp:
    server:
      - address: 127.0.0.10
        port: 8806  # Matching SMF's client port
  gtpu:
    server:
      - address: 127.0.0.10  # UPF binds GTP-U to its own IP
  metrics:
    server:
      - address: 127.0.0.10
        port: 9090
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dev: ogstun