services:
  mongodb:
    image: mongo:5.0
    container_name: open5gs_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: open5gs
      MONGO_INITDB_DATABASE: open5gs
    networks:
      default:
        ipv4_address: 10.53.1.2

  nrf:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_nrf
    restart: always
    environment:
      - COMPONENT_NAME=nrf-1
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    command: /opt/open5gs/bin/open5gs-nrfd
    networks:
      default:
        ipv4_address: 10.53.1.10

  scp:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_scp
    restart: always
    depends_on:
      - nrf
    environment:
      - COMPONENT_NAME=scp-1
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    command: /opt/open5gs/bin/open5gs-scpd
    networks:
      default:
        ipv4_address: 10.53.1.200

  amf:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_amf
    restart: always
    depends_on:
      - scp
      - nrf
    environment:
      - COMPONENT_NAME=amf-1
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
      - ./config/amf.yaml:/opt/open5gs/etc/open5gs/amf.yaml:ro
    expose:
      - "38412/sctp"
    ports:
      - "0.0.0.0:38412:38412/sctp"
    command: /opt/open5gs/bin/open5gs-amfd
    networks:
      default:
        ipv4_address: 10.53.1.12

  smf:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_smf
    restart: always
    depends_on:
      - scp
      - nrf
      - upf
    environment:
      - COMPONENT_NAME=smf-1
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    command: /opt/open5gs/bin/open5gs-smfd
    networks:
      default:
        ipv4_address: 10.53.1.13

  upf:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_upf
    restart: always
    depends_on:
      - nrf
    environment:
      - COMPONENT_NAME=upf-1
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    command: /opt/open5gs/bin/open5gs-upfd
    networks:
      default:
        ipv4_address: 10.53.1.14

  ausf:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_ausf
    restart: always
    depends_on:
      - scp
      - nrf
    environment:
      - COMPONENT_NAME=ausf-1
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    command: /opt/open5gs/bin/open5gs-ausfd
    networks:
      default:
        ipv4_address: 10.53.1.15

  udm:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_udm
    restart: always
    depends_on:
      - scp
      - nrf
    environment:
      - COMPONENT_NAME=udm-1
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    command: /opt/open5gs/bin/open5gs-udmd
    networks:
      default:
        ipv4_address: 10.53.1.16

  udr:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_udr
    restart: always
    depends_on:
      - mongodb
      - scp
      - nrf
    environment:
      - COMPONENT_NAME=udr-1
      - DB_URI=mongodb://root:open5gs@mongodb:27017/open5gs?authSource=admin
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    command: /opt/open5gs/bin/open5gs-udrd
    networks:
      default:
        ipv4_address: 10.53.1.17

  pcf:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_pcf
    restart: always
    depends_on:
      - mongodb
      - scp
      - nrf
    environment:
      - COMPONENT_NAME=pcf-1
      - DB_URI=mongodb://root:open5gs@mongodb:27017/open5gs?authSource=admin
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    command: /opt/open5gs/bin/open5gs-pcfd
    networks:
      default:
        ipv4_address: 10.53.1.18

  nssf:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_nssf
    restart: always
    depends_on:
      - scp
      - nrf
    environment:
      - COMPONENT_NAME=nssf-1
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    command: /opt/open5gs/bin/open5gs-nssfd
    networks:
      default:
        ipv4_address: 10.53.1.19

  bsf:
    image: openverso/open5gs:2.7.0
    container_name: open5gs_bsf
    restart: always
    depends_on:
      - mongodb
      - scp
      - nrf
    environment:
      - COMPONENT_NAME=bsf-1
      - DB_URI=mongodb://root:open5gs@mongodb:27017/open5gs?authSource=admin
    volumes:
      - ./log:/open5gs/install/var/log/open5gs
    command: /opt/open5gs/bin/open5gs-bsfd
    networks:
      default:
        ipv4_address: 10.53.1.20

  webui:
    image: openverso/open5gs-webui:2.7.0
    container_name: open5gs_webui
    depends_on:
      - mongodb
    restart: always
    environment:
      DB_URI: mongodb://root:open5gs@mongodb:27017/open5gs?authSource=admin
      NODE_ENV: development
    ports:
      - "9999:9999"
    networks:
      default:
        ipv4_address: 10.53.1.3

volumes:
  mongodb_data:

networks:
  default:
    driver: bridge
    name: open5gs
    ipam:
      config:
        - subnet: 10.53.1.0/24
          gateway: 10.53.1.1