logger:
  file: /workspace/logs/open5gs_20250626_095458/amf.log
  level: info

global:
  max_integrity_protected_data_rate: 
    uplink: 64kbps
    downlink: 64kbps

amf:
  sbi:
    server:
      - address: 127.0.0.5
        port: 7777
    client:
      scp:
        - uri: http://127.0.0.200:7777
  ngap:
    server:
      - address: 127.0.0.5
        port: 38412
  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 7
  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1
  security:
    integrity_order: [ NIA2, NIA1, NIA0 ]
    ciphering_order: [ NEA0, NEA1, NEA2 ]
  network_name:
    full: Open5GS
    short: Open5GS
  network_feature_support_5gs:
    enable: true
    ims_voice_over_ps_session: 0
    emc: 0
    emf: 0
    iwk_n26: 0
    mpsi: 0
    emcn3: 0
    mcsi: 0
  amf_name: open5gs-amf0
  time:
    t3502:
      value: 720
    t3512:
      value: 540
    t3513:
      minimum: 2
      value: 2
